### ISSUE TITLE
[質問]@helper.formのactionについて

### ISSUE THREAD

**Issue by zto-michishita** [iizuka-youhei/Play-framework-practice#4]
https://github.com/iizuka-youhei/Play-framework-practice/blob/e7f1d1f2608bb6c11873a1db8f3c0feffd0753c1/app/views/edit.scala.html#L7

[ask]
formの送り先をactionに入れる意味がドキュメントを読んでも理解できなかったので、質問します。

ここ、僕も調べたのですが、ボイラーテンプレート的な意味合いが強いかなと思って消して書いていたのですが、公式では変数actionに(@を付けるとscalaの処理になるので)に実行先を代入しているものが多く見受けられました。
ここの意味を知っていたら教えていただけると幸いです。

**Comment by iizuka-youhei** [comment]
送信先がどのアクションであるかを指定するために`actrion =`と書いているだけだと個人的には思っていてそれ以上考えたことがないので深い意味については正直わかりません…

**Comment by zto-michishita** [comment]
なるほど…

ありがとうございます！
