### ISSUE TITLE
ログインページの挙動について

### ISSUE THREAD

**Issue by zto-michishita** [iizuka-youhei/Play-framework-practice#6]
https://github.com/iizuka-youhei/Play-framework-practice/blob/fcf9ef775ebdb2c410ffa3dc42b8a4ff9c023863/app/views/login.scala.html#L7-L12

[ask]
ここの部分、何も入力せずにログインしようとするとエラーが起きるのですが、他のブランチで直していたりしますか？

**Comment by iizuka-youhei** [comment]
直していないです。バグを修正してPRしてもらえると助かります。

**Comment by zto-michishita** [comment]
ここの部分、Modelで良く使う`@Required`を使えば上手く動くと思うのですが、LoginのFormのmodelを作ってもいいですか？

**Comment by iizuka-youhei** [comment]
OKです。LoginのFormを作成してください！
